//
// Created by nerea on 18/10/2023.
//

#ifndef COLECCIONEJERCICIOSNOCIONESCLAVE2_FUNCIONES_H
#define COLECCIONEJERCICIOSNOCIONESCLAVE2_FUNCIONES_H


class funciones {

};


#endif //COLECCIONEJERCICIOSNOCIONESCLAVE2_FUNCIONES_H
